-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles Table (Users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );


-- Scores Table (Leaderboard)
create table public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  username text not null, -- Denormalized for performance
  date_key text not null, -- Format: YYYY-MM-DD
  moves integer not null,
  time_ms integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.scores enable row level security;

-- Policies for Scores
create policy "Scores are viewable by everyone."
  on public.scores for select
  using ( true );

create policy "Users can insert their own scores."
  on public.scores for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own scores."
  on public.scores for update
  using ( auth.uid() = user_id );

-- Create an index for faster leaderboard queries
create index scores_date_idx on public.scores (date_key);
create index scores_moves_time_idx on public.scores (date_key, moves asc, time_ms asc);
