-- ================================================
-- A/B TESTING SCHEMA
-- Run this in Supabase SQL Editor
-- ================================================

-- ================================================
-- EXPERIMENT ASSIGNMENTS TABLE
-- Tracks which variant each user is assigned to
-- ================================================
create table if not exists public.experiment_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  experiment_id text not null,
  variant text not null,
  assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Each user can only have one assignment per experiment
  unique(user_id, experiment_id)
);

-- Enable RLS
alter table public.experiment_assignments enable row level security;

-- RLS Policies
create policy "Users can view own assignments"
  on public.experiment_assignments for select
  using (auth.uid() = user_id);

create policy "Users can insert own assignments"
  on public.experiment_assignments for insert
  with check (auth.uid() = user_id);

create policy "Users can update own assignments"
  on public.experiment_assignments for update
  using (auth.uid() = user_id);

-- Indexes
create index if not exists exp_assign_user_idx on public.experiment_assignments (user_id);
create index if not exists exp_assign_exp_idx on public.experiment_assignments (experiment_id);

-- ================================================
-- EXPERIMENT EVENTS TABLE
-- Tracks events within experiments for analysis
-- ================================================
create table if not exists public.experiment_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  experiment_id text not null,
  variant text not null,
  event_type text not null,
  event_data jsonb default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.experiment_events enable row level security;

-- RLS Policies
create policy "Users can insert own events"
  on public.experiment_events for insert
  with check (auth.uid() = user_id);

create policy "Users can view own events"
  on public.experiment_events for select
  using (auth.uid() = user_id);

-- Indexes
create index if not exists exp_events_exp_idx on public.experiment_events (experiment_id);
create index if not exists exp_events_variant_idx on public.experiment_events (variant);
create index if not exists exp_events_type_idx on public.experiment_events (event_type);

-- ================================================
-- ANALYSIS FUNCTIONS
-- ================================================

-- Get variant distribution for an experiment
create or replace function get_experiment_distribution(p_experiment_id text)
returns table (
  variant text,
  user_count bigint,
  percentage numeric
)
language sql
security definer
as $$
  with total as (
    select count(*) as cnt from public.experiment_assignments 
    where experiment_id = p_experiment_id
  )
  select 
    variant,
    count(*) as user_count,
    round((count(*)::numeric / nullif((select cnt from total), 0)) * 100, 2) as percentage
  from public.experiment_assignments
  where experiment_id = p_experiment_id
  group by variant
  order by variant;
$$;

-- Get conversion rate for an experiment
create or replace function get_experiment_conversions(
  p_experiment_id text, 
  p_conversion_event text
)
returns table (
  variant text,
  total_users bigint,
  converted_users bigint,
  conversion_rate numeric
)
language sql
security definer
as $$
  with assignments as (
    select user_id, variant
    from public.experiment_assignments
    where experiment_id = p_experiment_id
  ),
  conversions as (
    select distinct user_id
    from public.experiment_events
    where experiment_id = p_experiment_id 
    and event_type = p_conversion_event
  )
  select 
    a.variant,
    count(distinct a.user_id) as total_users,
    count(distinct c.user_id) as converted_users,
    round(
      (count(distinct c.user_id)::numeric / nullif(count(distinct a.user_id), 0)) * 100, 
      2
    ) as conversion_rate
  from assignments a
  left join conversions c on a.user_id = c.user_id
  group by a.variant
  order by a.variant;
$$;
