-- ================================================
-- ANALYTICS TABLES FOR FLOWSTATE
-- Run this in Supabase SQL Editor
-- ================================================

-- ================================================
-- USER VISITS TABLE
-- Tracks every user session with IP and device info
-- ================================================
create table if not exists public.user_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  
  -- IP & Location
  ip_address text,
  country text,
  city text,
  timezone text,
  
  -- Device Info
  user_agent text,
  platform text,
  browser text,
  os text,
  screen_width integer,
  screen_height integer,
  is_mobile boolean default false,
  
  -- Referral
  referrer text,
  page_url text,
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_visits enable row level security;

-- RLS Policies
-- Users can insert their own visits
create policy "Users can insert own visits"
  on public.user_visits for insert
  with check (auth.uid() = user_id);

-- Users can view their own visits (optional)
create policy "Users can view own visits"
  on public.user_visits for select
  using (auth.uid() = user_id);

-- Indexes for analytics queries
create index if not exists visits_user_idx on public.user_visits (user_id);
create index if not exists visits_created_idx on public.user_visits (created_at);
create index if not exists visits_country_idx on public.user_visits (country);

-- ================================================
-- ANALYTICS EVENTS TABLE
-- Tracks custom events (game start, win, purchases, etc)
-- ================================================
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  
  -- Event Info
  event_type text not null,
  event_data jsonb default '{}' not null,
  page_url text,
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.analytics_events enable row level security;

-- RLS Policies
create policy "Users can insert own events"
  on public.analytics_events for insert
  with check (auth.uid() = user_id);

create policy "Users can view own events"
  on public.analytics_events for select
  using (auth.uid() = user_id);

-- Indexes
create index if not exists events_user_idx on public.analytics_events (user_id);
create index if not exists events_type_idx on public.analytics_events (event_type);
create index if not exists events_created_idx on public.analytics_events (created_at);

-- ================================================
-- ADMIN VIEW: Daily Statistics
-- (Optional - for admin dashboard)
-- ================================================

-- Create a function to get daily stats
create or replace function get_daily_stats(days_back integer default 7)
returns table (
  stat_date date,
  unique_users bigint,
  total_visits bigint,
  total_games bigint,
  total_wins bigint
)
language sql
security definer
as $$
  with date_series as (
    select generate_series(
      current_date - (days_back - 1),
      current_date,
      '1 day'::interval
    )::date as stat_date
  )
  select 
    ds.stat_date,
    coalesce(count(distinct uv.user_id), 0) as unique_users,
    coalesce(count(uv.id), 0) as total_visits,
    coalesce(count(case when ae.event_type = 'game_start' then 1 end), 0) as total_games,
    coalesce(count(case when ae.event_type = 'game_win' then 1 end), 0) as total_wins
  from date_series ds
  left join public.user_visits uv on date(uv.created_at) = ds.stat_date
  left join public.analytics_events ae on date(ae.created_at) = ds.stat_date
  group by ds.stat_date
  order by ds.stat_date desc;
$$;

-- ================================================
-- ADMIN VIEW: Country Statistics
-- ================================================
create or replace function get_country_stats()
returns table (
  country text,
  visit_count bigint,
  unique_users bigint
)
language sql
security definer
as $$
  select 
    coalesce(country, 'Unknown') as country,
    count(*) as visit_count,
    count(distinct user_id) as unique_users
  from public.user_visits
  where created_at > now() - interval '30 days'
  group by country
  order by visit_count desc
  limit 20;
$$;

-- ================================================
-- ADMIN VIEW: Device Statistics
-- ================================================
create or replace function get_device_stats()
returns table (
  browser text,
  os text,
  is_mobile boolean,
  visit_count bigint
)
language sql
security definer
as $$
  select 
    browser,
    os,
    is_mobile,
    count(*) as visit_count
  from public.user_visits
  where created_at > now() - interval '30 days'
  group by browser, os, is_mobile
  order by visit_count desc
  limit 20;
$$;

-- ================================================
-- ADMIN VIEW: Event Statistics
-- ================================================
create or replace function get_event_stats()
returns table (
  event_type text,
  event_count bigint,
  unique_users bigint
)
language sql
security definer
as $$
  select 
    event_type,
    count(*) as event_count,
    count(distinct user_id) as unique_users
  from public.analytics_events
  where created_at > now() - interval '7 days'
  group by event_type
  order by event_count desc;
$$;
