-- ================================================
-- Cloud Sync Tables for FlowState Game
-- Run this in Supabase SQL Editor
-- ================================================

-- Enable UUID extension (if not already enabled)
create extension if not exists "uuid-ossp";

-- ================================================
-- USER PROGRESS TABLE
-- Stores XP, level, wins, badges etc.
-- ================================================
create table if not exists public.user_progress (
  id uuid references auth.users not null primary key,
  xp integer default 0 not null,
  level integer default 1 not null,
  total_wins integer default 0 not null,
  fastest_win_ms integer,
  consecutive_no_hint_wins integer default 0 not null,
  badges text[] default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_progress enable row level security;

-- RLS Policies
create policy "Users can view own progress"
  on public.user_progress for select
  using (auth.uid() = id);

create policy "Users can insert own progress"
  on public.user_progress for insert
  with check (auth.uid() = id);

create policy "Users can update own progress"
  on public.user_progress for update
  using (auth.uid() = id);

-- ================================================
-- USER ECONOMY TABLE
-- Stores coins, spending history
-- ================================================
create table if not exists public.user_economy (
  id uuid references auth.users not null primary key,
  coins integer default 0 not null,
  total_earned integer default 0 not null,
  total_spent integer default 0 not null,
  unlocked_items text[] default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_economy enable row level security;

-- RLS Policies
create policy "Users can view own economy"
  on public.user_economy for select
  using (auth.uid() = id);

create policy "Users can insert own economy"
  on public.user_economy for insert
  with check (auth.uid() = id);

create policy "Users can update own economy"
  on public.user_economy for update
  using (auth.uid() = id);

-- ================================================
-- USER INVENTORY TABLE
-- Stores powerup counts
-- ================================================
create table if not exists public.user_inventory (
  id uuid references auth.users not null primary key,
  hints integer default 3 not null,
  undos integer default 3 not null,
  freezes integer default 3 not null,
  coin_boosts integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_inventory enable row level security;

-- RLS Policies
create policy "Users can view own inventory"
  on public.user_inventory for select
  using (auth.uid() = id);

create policy "Users can insert own inventory"
  on public.user_inventory for insert
  with check (auth.uid() = id);

create policy "Users can update own inventory"
  on public.user_inventory for update
  using (auth.uid() = id);

-- ================================================
-- CAMPAIGN PROGRESS TABLE
-- Stores completed levels and stars
-- ================================================
create table if not exists public.campaign_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  level_id text not null,
  stars integer default 0 not null check (stars >= 0 and stars <= 3),
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Unique constraint for upsert
  unique(user_id, level_id)
);

-- Enable RLS
alter table public.campaign_progress enable row level security;

-- RLS Policies
create policy "Users can view own campaign progress"
  on public.campaign_progress for select
  using (auth.uid() = user_id);

create policy "Users can insert own campaign progress"
  on public.campaign_progress for insert
  with check (auth.uid() = user_id);

create policy "Users can update own campaign progress"
  on public.campaign_progress for update
  using (auth.uid() = user_id);

-- Index for faster queries
create index if not exists campaign_user_idx on public.campaign_progress (user_id);

-- ================================================
-- GAME SESSIONS TABLE
-- Analytics for all game sessions
-- ================================================
create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  mode text not null, -- daily, campaign, endless, speedrun, weekly
  date_key text, -- YYYY-MM-DD format for daily modes
  moves integer not null,
  time_ms integer not null,
  won boolean default false not null,
  used_hint boolean default false not null,
  powerups_used jsonb default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.game_sessions enable row level security;

-- RLS Policies
create policy "Users can view own sessions"
  on public.game_sessions for select
  using (auth.uid() = user_id);

create policy "Users can insert own sessions"
  on public.game_sessions for insert
  with check (auth.uid() = user_id);

-- Indexes for analytics queries
create index if not exists sessions_user_idx on public.game_sessions (user_id);
create index if not exists sessions_mode_idx on public.game_sessions (mode);
create index if not exists sessions_date_idx on public.game_sessions (date_key);
