-- ================================================
-- ERROR TRACKING SCHEMA
-- Run this in Supabase SQL Editor
-- ================================================

-- ================================================
-- ERROR LOGS TABLE
-- ================================================
create table if not exists public.error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  
  -- Error Info
  message text not null,
  stack text,
  component text,
  action text,
  context_data jsonb default '{}',
  severity text default 'error' check (severity in ('error', 'warning', 'info')),
  
  -- Device Info
  browser text,
  os text,
  platform text,
  is_mobile boolean default false,
  screen_width integer,
  screen_height integer,
  user_agent text,
  page_url text,
  
  -- Timestamps
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.error_logs enable row level security;

-- RLS Policies - Anyone can insert errors (even anonymous)
create policy "Anyone can insert errors"
  on public.error_logs for insert
  with check (true);

-- Only authenticated users can view their own errors
create policy "Users can view own errors"
  on public.error_logs for select
  using (auth.uid() = user_id);

-- Indexes for faster queries
create index if not exists error_logs_user_idx on public.error_logs (user_id);
create index if not exists error_logs_created_idx on public.error_logs (created_at);
create index if not exists error_logs_severity_idx on public.error_logs (severity);
create index if not exists error_logs_component_idx on public.error_logs (component);

-- ================================================
-- ADMIN FUNCTION: Get Error Stats
-- ================================================
create or replace function get_error_stats()
returns json
language sql
security definer
as $$
  select json_build_object(
    'totalErrors', (select count(*) from public.error_logs where severity = 'error'),
    'todayErrors', (select count(*) from public.error_logs where severity = 'error' and created_at > now() - interval '1 day'),
    'topErrors', (
      select coalesce(json_agg(row_to_json(t)), '[]'::json)
      from (
        select message, count(*) as count
        from public.error_logs
        where severity = 'error' and created_at > now() - interval '7 days'
        group by message
        order by count desc
        limit 10
      ) t
    )
  );
$$;
