-- ================================================
-- FLOWSTATE - COMPLETE DATABASE SCHEMA
-- Run this ONCE in Supabase SQL Editor
-- ================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ================================================
-- 1. PROFILES TABLE (Users)
-- ================================================
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select using (true);

create policy "Users can insert their own profile."
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile."
  on public.profiles for update using (auth.uid() = id);

-- ================================================
-- 2. SCORES TABLE (Leaderboard)
-- ================================================
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  username text not null,
  date_key text not null,
  moves integer not null,
  time_ms integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.scores enable row level security;

create policy "Scores are viewable by everyone."
  on public.scores for select using (true);

create policy "Users can insert their own scores."
  on public.scores for insert with check (auth.uid() = user_id);

create index if not exists scores_date_idx on public.scores (date_key);
create index if not exists scores_moves_time_idx on public.scores (date_key, moves asc, time_ms asc);

-- ================================================
-- 3. USER PROGRESS TABLE
-- ================================================
create table if not exists public.user_progress (
  id uuid references auth.users not null primary key,
  xp integer default 0 not null,
  level integer default 1 not null,
  total_wins integer default 0 not null,
  fastest_win_ms integer,
  consecutive_no_hint_wins integer default 0 not null,
  badges text[] default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_progress enable row level security;

create policy "Users can view own progress"
  on public.user_progress for select using (auth.uid() = id);

create policy "Users can insert own progress"
  on public.user_progress for insert with check (auth.uid() = id);

create policy "Users can update own progress"
  on public.user_progress for update using (auth.uid() = id);

-- ================================================
-- 4. USER ECONOMY TABLE
-- ================================================
create table if not exists public.user_economy (
  id uuid references auth.users not null primary key,
  coins integer default 0 not null,
  total_earned integer default 0 not null,
  total_spent integer default 0 not null,
  unlocked_items text[] default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_economy enable row level security;

create policy "Users can view own economy"
  on public.user_economy for select using (auth.uid() = id);

create policy "Users can insert own economy"
  on public.user_economy for insert with check (auth.uid() = id);

create policy "Users can update own economy"
  on public.user_economy for update using (auth.uid() = id);

-- ================================================
-- 5. USER INVENTORY TABLE
-- ================================================
create table if not exists public.user_inventory (
  id uuid references auth.users not null primary key,
  hints integer default 3 not null,
  undos integer default 3 not null,
  freezes integer default 3 not null,
  coin_boosts integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_inventory enable row level security;

create policy "Users can view own inventory"
  on public.user_inventory for select using (auth.uid() = id);

create policy "Users can insert own inventory"
  on public.user_inventory for insert with check (auth.uid() = id);

create policy "Users can update own inventory"
  on public.user_inventory for update using (auth.uid() = id);

-- ================================================
-- 6. CAMPAIGN PROGRESS TABLE
-- ================================================
create table if not exists public.campaign_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  level_id text not null,
  stars integer default 0 not null check (stars >= 0 and stars <= 3),
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, level_id)
);

alter table public.campaign_progress enable row level security;

create policy "Users can view own campaign progress"
  on public.campaign_progress for select using (auth.uid() = user_id);

create policy "Users can insert own campaign progress"
  on public.campaign_progress for insert with check (auth.uid() = user_id);

create policy "Users can update own campaign progress"
  on public.campaign_progress for update using (auth.uid() = user_id);

create index if not exists campaign_user_idx on public.campaign_progress (user_id);

-- ================================================
-- 7. GAME SESSIONS TABLE (Analytics)
-- ================================================
create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  mode text not null,
  date_key text,
  moves integer not null,
  time_ms integer not null,
  won boolean default false not null,
  used_hint boolean default false not null,
  powerups_used jsonb default '{}' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.game_sessions enable row level security;

create policy "Users can view own sessions"
  on public.game_sessions for select using (auth.uid() = user_id);

create policy "Users can insert own sessions"
  on public.game_sessions for insert with check (auth.uid() = user_id);

create index if not exists sessions_user_idx on public.game_sessions (user_id);
create index if not exists sessions_mode_idx on public.game_sessions (mode);
create index if not exists sessions_date_idx on public.game_sessions (date_key);
