-- ================================================
-- FLOWSTATE PRODUCTION DATABASE SCHEMA
-- Version: 3.0 (Production Ready - All-in-One)
-- Last Updated: 2026-01-20
-- ================================================
-- Bu dosyayı Supabase SQL Editor'da TEK SEFERDE çalıştırın.
-- Tüm tablolar, fonksiyonlar ve politikalar dahildir.
-- ================================================

-- Enable required extensions
create extension if not exists "uuid-ossp";

-- ================================================
-- UTILITY FUNCTIONS
-- ================================================

-- Auto-update timestamp trigger function
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ================================================
-- 1. PROFILES TABLE (User Identity)
-- ================================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  display_name text,
  avatar_url text,
  is_banned boolean default false not null,
  ban_reason text,
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

alter table public.profiles enable row level security;

-- RLS Policies
create policy "Public profiles are viewable by everyone"
  on public.profiles for select using (true);

create policy "Users can insert their own profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

-- Trigger for auto-update timestamp
drop trigger if exists update_profiles_timestamp on public.profiles;
create trigger update_profiles_timestamp
  before update on public.profiles
  for each row execute function update_updated_at();

-- Index for username lookups
create index if not exists profiles_username_idx on public.profiles (username);

-- ================================================
-- 2. SCORES TABLE (Leaderboard - CORE)
-- ================================================
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  username text not null,
  date_key text not null,
  moves integer not null check (moves > 0),
  time_ms integer not null check (time_ms > 0),
  created_at timestamp with time zone default now() not null,
  -- Unique constraint: One score per user per day
  unique(user_id, date_key)
);

alter table public.scores enable row level security;

-- RLS Policies
create policy "Scores are viewable by everyone"
  on public.scores for select using (true);

create policy "Users can insert their own scores"
  on public.scores for insert with check (auth.uid() = user_id);

create policy "Users can update their own scores"
  on public.scores for update using (auth.uid() = user_id);

-- Performance indexes
create index if not exists scores_date_idx on public.scores (date_key);
create index if not exists scores_user_idx on public.scores (user_id);
create index if not exists scores_ranking_idx on public.scores (date_key, moves asc, time_ms asc);

-- ================================================
-- 3. USER VISITS TABLE (Analytics)
-- ================================================
create table if not exists public.user_visits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  ip_address text,
  country text,
  city text,
  timezone text,
  user_agent text,
  platform text,
  browser text,
  os text,
  screen_width integer,
  screen_height integer,
  is_mobile boolean default false,
  referrer text,
  page_url text,
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null
);

alter table public.user_visits enable row level security;

-- RLS Policies
create policy "Users can insert own visits"
  on public.user_visits for insert with check (auth.uid() = user_id);

create policy "Users can view own visits"
  on public.user_visits for select using (auth.uid() = user_id);

-- Indexes
create index if not exists visits_user_idx on public.user_visits (user_id);
create index if not exists visits_created_idx on public.user_visits (created_at);
create index if not exists visits_country_idx on public.user_visits (country);

-- ================================================
-- 4. ANALYTICS EVENTS TABLE
-- ================================================
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  event_type text not null,
  event_data jsonb default '{}' not null,
  page_url text,
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null
);

alter table public.analytics_events enable row level security;

-- RLS Policies
create policy "Users can insert own events"
  on public.analytics_events for insert with check (auth.uid() = user_id);

create policy "Users can view own events"
  on public.analytics_events for select using (auth.uid() = user_id);

-- Indexes
create index if not exists events_user_idx on public.analytics_events (user_id);
create index if not exists events_type_idx on public.analytics_events (event_type);
create index if not exists events_created_idx on public.analytics_events (created_at);

-- ================================================
-- 5. USER PROGRESS TABLE (XP, Level, Badges)
-- ================================================
create table if not exists public.user_progress (
  id uuid references auth.users on delete cascade not null primary key,
  xp integer default 0 not null,
  level integer default 1 not null,
  total_wins integer default 0 not null,
  total_games integer default 0 not null,
  fastest_win_ms integer,
  consecutive_no_hint_wins integer default 0 not null,
  current_streak integer default 0 not null,
  max_streak integer default 0 not null,
  badges text[] default '{}' not null,
  last_played_at timestamp with time zone,
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

alter table public.user_progress enable row level security;

create policy "Users can view own progress"
  on public.user_progress for select using (auth.uid() = id);

create policy "Users can insert own progress"
  on public.user_progress for insert with check (auth.uid() = id);

create policy "Users can update own progress"
  on public.user_progress for update using (auth.uid() = id);

drop trigger if exists update_user_progress_timestamp on public.user_progress;
create trigger update_user_progress_timestamp
  before update on public.user_progress
  for each row execute function update_updated_at();

-- ================================================
-- 6. USER ECONOMY TABLE (Coins)
-- ================================================
create table if not exists public.user_economy (
  id uuid references auth.users on delete cascade not null primary key,
  coins integer default 0 not null check (coins >= 0),
  gems integer default 0 not null check (gems >= 0),
  total_earned integer default 0 not null,
  total_spent integer default 0 not null,
  unlocked_items text[] default '{}' not null,
  unlocked_themes text[] default '{"default"}' not null,
  active_theme text default 'default' not null,
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

alter table public.user_economy enable row level security;

create policy "Users can view own economy"
  on public.user_economy for select using (auth.uid() = id);

create policy "Users can insert own economy"
  on public.user_economy for insert with check (auth.uid() = id);

create policy "Users can update own economy"
  on public.user_economy for update using (auth.uid() = id);

drop trigger if exists update_user_economy_timestamp on public.user_economy;
create trigger update_user_economy_timestamp
  before update on public.user_economy
  for each row execute function update_updated_at();

-- ================================================
-- 7. USER INVENTORY TABLE (Power-ups)
-- ================================================
create table if not exists public.user_inventory (
  id uuid references auth.users on delete cascade not null primary key,
  hints integer default 3 not null check (hints >= 0),
  undos integer default 3 not null check (undos >= 0),
  freezes integer default 3 not null check (freezes >= 0),
  time_extensions integer default 0 not null check (time_extensions >= 0),
  coin_boosts integer default 0 not null check (coin_boosts >= 0),
  multipliers integer default 0 not null check (multipliers >= 0),
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

alter table public.user_inventory enable row level security;

create policy "Users can view own inventory"
  on public.user_inventory for select using (auth.uid() = id);

create policy "Users can insert own inventory"
  on public.user_inventory for insert with check (auth.uid() = id);

create policy "Users can update own inventory"
  on public.user_inventory for update using (auth.uid() = id);

drop trigger if exists update_user_inventory_timestamp on public.user_inventory;
create trigger update_user_inventory_timestamp
  before update on public.user_inventory
  for each row execute function update_updated_at();

-- ================================================
-- 8. CAMPAIGN PROGRESS TABLE
-- ================================================
create table if not exists public.campaign_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  level_id text not null,
  stars integer default 0 not null check (stars >= 0 and stars <= 3),
  moves integer,
  time_ms integer,
  completed_at timestamp with time zone default now() not null,
  unique(user_id, level_id)
);

alter table public.campaign_progress enable row level security;

create policy "Users can view own campaign progress"
  on public.campaign_progress for select using (auth.uid() = user_id);

create policy "Users can insert own campaign progress"
  on public.campaign_progress for insert with check (auth.uid() = user_id);

create policy "Users can update own campaign progress"
  on public.campaign_progress for update using (auth.uid() = user_id);

create index if not exists campaign_user_idx on public.campaign_progress (user_id);
create index if not exists campaign_level_idx on public.campaign_progress (level_id);

-- ================================================
-- 9. GAME SESSIONS TABLE (Detailed Analytics)
-- ================================================
create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  mode text not null,
  date_key text,
  level_id text,
  moves integer not null,
  time_ms integer not null,
  won boolean default false not null,
  used_hint boolean default false not null,
  powerups_used jsonb default '{}' not null,
  score integer default 0 not null,
  difficulty text default 'normal',
  local_time text,
  user_timezone text,
  created_at timestamp with time zone default now() not null
);

alter table public.game_sessions enable row level security;

create policy "Users can view own sessions"
  on public.game_sessions for select using (auth.uid() = user_id);

create policy "Users can insert own sessions"
  on public.game_sessions for insert with check (auth.uid() = user_id);

create index if not exists sessions_user_idx on public.game_sessions (user_id);
create index if not exists sessions_mode_idx on public.game_sessions (mode);
create index if not exists sessions_date_idx on public.game_sessions (date_key);
create index if not exists sessions_won_idx on public.game_sessions (won);
create index if not exists sessions_created_idx on public.game_sessions (created_at);

-- ================================================
-- 10. ERROR LOGS TABLE
-- ================================================
create table if not exists public.error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  message text not null,
  stack text,
  component text,
  action text,
  context_data jsonb default '{}',
  severity text default 'error' check (severity in ('error', 'warning', 'info')),
  browser text,
  os text,
  platform text,
  is_mobile boolean default false,
  screen_width integer,
  screen_height integer,
  user_agent text,
  page_url text,
  created_at timestamp with time zone default now() not null
);

alter table public.error_logs enable row level security;

-- Anyone can insert errors (including anonymous users)
create policy "Anyone can insert errors"
  on public.error_logs for insert with check (true);

create policy "Users can view own errors"
  on public.error_logs for select using (auth.uid() = user_id);

create index if not exists error_logs_user_idx on public.error_logs (user_id);
create index if not exists error_logs_created_idx on public.error_logs (created_at);
create index if not exists error_logs_severity_idx on public.error_logs (severity);

-- ================================================
-- 11. REFERRAL SYSTEM TABLES
-- ================================================
create table if not exists public.referral_codes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  code text not null unique,
  usage_count integer default 0 not null,
  created_at timestamp with time zone default now() not null
);

alter table public.referral_codes enable row level security;

create policy "Anyone can view referral codes"
  on public.referral_codes for select using (true);

create policy "Users can create own referral code"
  on public.referral_codes for insert with check (auth.uid() = user_id);

create policy "Users can update own referral code"
  on public.referral_codes for update using (auth.uid() = user_id);

create index if not exists referral_code_idx on public.referral_codes (code);

create table if not exists public.referral_usages (
  id bigint generated by default as identity primary key,
  referrer_id uuid references auth.users not null,
  referee_id uuid references auth.users not null,
  code text not null,
  claimed boolean default false not null,
  created_at timestamp with time zone default now() not null,
  unique(referee_id)
);

alter table public.referral_usages enable row level security;

create policy "Users can view referrals they made"
  on public.referral_usages for select using (auth.uid() = referrer_id);

create policy "Users can insert referral usage"
  on public.referral_usages for insert with check (auth.uid() = referee_id);

create policy "Referrers can update their referral claims"
  on public.referral_usages for update using (auth.uid() = referrer_id);

create index if not exists referral_referrer_idx on public.referral_usages (referrer_id);
create index if not exists referral_referee_idx on public.referral_usages (referee_id);

-- ================================================
-- 12. A/B TESTING TABLES
-- ================================================
create table if not exists public.experiment_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  experiment_id text not null,
  variant text not null,
  assigned_at timestamp with time zone default now() not null,
  unique(user_id, experiment_id)
);

alter table public.experiment_assignments enable row level security;

create policy "Users can view own assignments"
  on public.experiment_assignments for select using (auth.uid() = user_id);

create policy "Users can insert own assignments"
  on public.experiment_assignments for insert with check (auth.uid() = user_id);

create index if not exists exp_assign_user_idx on public.experiment_assignments (user_id);
create index if not exists exp_assign_exp_idx on public.experiment_assignments (experiment_id);

create table if not exists public.experiment_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  experiment_id text not null,
  variant text not null,
  event_type text not null,
  event_data jsonb default '{}',
  created_at timestamp with time zone default now() not null
);

alter table public.experiment_events enable row level security;

create policy "Users can insert own experiment events"
  on public.experiment_events for insert with check (auth.uid() = user_id);

create policy "Users can view own experiment events"
  on public.experiment_events for select using (auth.uid() = user_id);

create index if not exists exp_events_exp_idx on public.experiment_events (experiment_id);
create index if not exists exp_events_variant_idx on public.experiment_events (variant);

-- ================================================
-- HELPER FUNCTIONS
-- ================================================

-- Get user rank for a specific date
create or replace function get_user_rank(p_user_id uuid, p_date_key text)
returns integer as $$
declare
  user_rank integer;
begin
  select rank into user_rank
  from (
    select user_id, rank() over (order by moves asc, time_ms asc) as rank
    from public.scores
    where date_key = p_date_key
  ) ranked
  where user_id = p_user_id;
  
  return coalesce(user_rank, 0);
end;
$$ language plpgsql security definer;

-- Get daily statistics (for admin)
create or replace function get_daily_stats(days_back integer default 7)
returns table (
  stat_date date,
  unique_users bigint,
  total_visits bigint,
  total_games bigint,
  total_wins bigint
)
language sql
security definer
as $$
  with date_series as (
    select generate_series(
      current_date - (days_back - 1),
      current_date,
      '1 day'::interval
    )::date as stat_date
  )
  select 
    ds.stat_date,
    coalesce(count(distinct uv.user_id), 0) as unique_users,
    coalesce(count(uv.id), 0) as total_visits,
    coalesce((select count(*) from public.game_sessions gs where date(gs.created_at) = ds.stat_date), 0) as total_games,
    coalesce((select count(*) from public.game_sessions gs where date(gs.created_at) = ds.stat_date and gs.won = true), 0) as total_wins
  from date_series ds
  left join public.user_visits uv on date(uv.created_at) = ds.stat_date
  group by ds.stat_date
  order by ds.stat_date desc;
$$;

-- Get country statistics
create or replace function get_country_stats()
returns table (
  country text,
  visit_count bigint,
  unique_users bigint
)
language sql
security definer
as $$
  select 
    coalesce(country, 'Unknown') as country,
    count(*) as visit_count,
    count(distinct user_id) as unique_users
  from public.user_visits
  where created_at > now() - interval '30 days'
  group by country
  order by visit_count desc
  limit 20;
$$;

-- Get referral stats for a user
create or replace function get_referral_stats(p_user_id uuid)
returns json
language sql
security definer
as $$
  select json_build_object(
    'totalReferrals', coalesce((
      select usage_count from public.referral_codes where user_id = p_user_id
    ), 0),
    'referralCode', (
      select code from public.referral_codes where user_id = p_user_id
    ),
    'unclaimedCount', coalesce((
      select count(*) from public.referral_usages 
      where referrer_id = p_user_id and claimed = false
    ), 0)
  );
$$;

-- ================================================
-- END OF SCHEMA
-- ================================================
-- Schema is ready! Run this file in Supabase SQL Editor.
-- ================================================
