-- ================================================
-- REFERRAL SYSTEM SCHEMA
-- Run this in Supabase SQL Editor
-- ================================================

-- ================================================
-- REFERRAL CODES TABLE
-- ================================================
create table if not exists public.referral_codes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  code text not null unique,
  usage_count integer default 0 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.referral_codes enable row level security;

-- RLS Policies
create policy "Anyone can view referral codes"
  on public.referral_codes for select
  using (true);

create policy "Users can create own referral code"
  on public.referral_codes for insert
  with check (auth.uid() = user_id);

create policy "Users can update own referral code"
  on public.referral_codes for update
  using (auth.uid() = user_id);

-- Index for fast code lookup
create index if not exists referral_code_idx on public.referral_codes (code);

-- ================================================
-- REFERRAL USAGES TABLE
-- ================================================
create table if not exists public.referral_usages (
  id bigint generated by default as identity primary key,
  referrer_id uuid references auth.users not null,
  referee_id uuid references auth.users not null,
  code text not null,
  claimed boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Each user can only use one referral code
  unique(referee_id)
);

-- Enable RLS
alter table public.referral_usages enable row level security;

-- RLS Policies
create policy "Users can view referrals they made"
  on public.referral_usages for select
  using (auth.uid() = referrer_id);

create policy "Users can insert referral usage"
  on public.referral_usages for insert
  with check (auth.uid() = referee_id);

create policy "Referrers can update their referral claims"
  on public.referral_usages for update
  using (auth.uid() = referrer_id);

-- Indexes
create index if not exists referral_referrer_idx on public.referral_usages (referrer_id);
create index if not exists referral_referee_idx on public.referral_usages (referee_id);

-- ================================================
-- FUNCTION: Get user's referral stats
-- ================================================
create or replace function get_referral_stats(p_user_id uuid)
returns json
language sql
security definer
as $$
  select json_build_object(
    'totalReferrals', coalesce((
      select usage_count from public.referral_codes where user_id = p_user_id
    ), 0),
    'referralCode', (
      select code from public.referral_codes where user_id = p_user_id
    ),
    'unclaimedCount', coalesce((
      select count(*) from public.referral_usages 
      where referrer_id = p_user_id and claimed = false
    ), 0)
  );
$$;
